replicaCount: 1
namespace: optikube

images:
  dashboard:
    repository: optikube/optikube-dashboard
    tag: "demo"
    pullPolicy: Always
  operator:
    repository: optikube/optikube-operator
    tag: "latest"
    pullPolicy: Always
  redis:
    repository: redis
    tag: "latest"
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: optikube-svc-account
  annotations: {}

resources:
  dashboard:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  operator:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  redis:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      cpu: "50m"
      memory: "64Mi"

services:
  dashboard:
    type: ClusterIP
    port: 3000
  operator:
    type: LoadBalancer
    port: 8080
  redis:
    type: ClusterIP
    port: 6379

dependencies:
  - name: cost-analyzer
    alias: kubecost
    version: "2.2.2"
    repository: "https://kubecost.github.io/cost-analyzer/"
  - name: keda
    version: "2.14.2"
    repository: "https://kedacore.github.io/charts"

rbac:
  create: true
  rules:
    - apiGroups: ["", "apps", "autoscaling", "keda.sh"]
      resources: ["*"]
      verbs: ["*"]

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelay: 30
  timeout: 10
  period: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelay: 30
  timeout: 10
  period: 10

ingress:
  enabled: false
  annotations: {}

autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}

kubecost:
  global:
    grafana:
      enabled: false
    prometheus:
      enabled: false
    thanos:
      enabled: false
    kubecostMetrics:
      enabled: false

  kubecostFrontend:
    enabled: false

  networkCosts:
    enabled: false

  serviceMonitor:
    enabled: false

  cloudCost:
    enabled: false

  persistentVolume:
    enabled: false

  kubecostModel:
    enabled: true  # must stay true for it to run, but disable its PVC
    persistentVolume:
      enabled: false
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"

  prometheus:
    enabled: false
    server:
      enabled: false
      persistentVolume:
        enabled: false